parameters:
#    john_article.example.class: John\ArticleBundle\Example

services:
#    john_article.example:
#        class: %john_article.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    john_article.unique.tag:
         class: John\ArticleBundle\Event\EventListener\UniqueTag
         tags:
            - {name: doctrine.event_listener, event: prePersist}
            - {name: doctrine.event_listener, event: preUpdate}

    john_article_activate:
          class: John\ArticleBundle\Event\EventListener\ArticleListener
          arguments: [@doctrine.orm.entity_manager, @service_container]
          tags:
             - {name: kernel.event_listener, event: article.activate, method: setPictureFillTags }
             - {name: kernel.event_listener, event: kernel.terminate, method: sendAuthorEmail}