parameters:
#    john_article.example.class: John\ArticleBundle\Example

services:
#    john_article.example:
#        class: %john_article.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    john_article.unique.tag:
         class: John\ArticleBundle\EventListener\UniqueTag
         tags:
            - {name: doctrine.event_listener, event: prePersist}
            - {name: doctrine.event_listener, event: preUpdate}