imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        #assets_version: 6
        #assets_version_format: "%%s?v=%%s"
            engines: ['twig']
            assets_base_urls:
                http: []
                ssl: []
            packages:
                cdn:
                    base_urls:
                        http: []
                        ssl: []
                cdn_static:
                    base_urls:
                        http: []
                        ssl: []


    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    read_from:            "%kernel.root_dir%/../web/"
    bundles:        [JohnSavantBundle,JohnAdminBundle,JohnArticleBundle]
    #java: C:\Program Files (x86)\Java\jre6\bin\java.exe
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
           #jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        #yui_js:
           #jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        uglifyjs:
          #bin: "C:/Users/Veronica/AppData/Roaming/npm/node_modules/uglify-js/bin/uglifyjs"
          bin: "C:/Users/IvanI/AppData/Roaming/npm/node_modules/uglify-js/bin/uglifyjs"


        uglifycss:
          #bin:  "C:/Users/Veronica/AppData/Roaming/npm/node_modules/uglifycss/uglifycss"
          bin:  "C:/Users/IvanI/AppData/Roaming/npm/node_modules/uglifycss/uglifycss"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

stof_doctrine_extensions:
    default_locale: en_US
    orm:
       default:
          sluggable: true

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        my_thumb:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
        strip: ~

    #loaders:
       # default:
           #filesystem:
               #data_root:  %kernel.root_dir%/../web/uploads/article_images/temp
