john_profile:
    resource: "@JohnProfileBundle/Resources/config/routing.yml"
    prefix:   /profile

john_users:
    resource: "@JohnUsersBundle/Resources/config/routing.yml"
    prefix:   /



john_admin:
    resource: "@JohnAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

john_savant:
    resource: "@JohnSavantBundle/Resources/config/routing.yml"
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

