security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    firewalls:
       secured_area:
           pattern: ^/
           anonymous: ~
           form_login:
              login_path: /login
              check_path: /login_check
           logout:
              path: /logout
              target: /

    access_control:
              - {path: ^/admin, roles: ROLE_ADMIN}
              - {path: ^/profile, roles: ROLE_USER}

    providers:
              database_provider:
                     entity: {class: JohnSavantBundle:User, property: email}

    encoders:
         John\SavantBundle\Entity\User: sha512