security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    firewalls:
       secured_area:
           #switch_user: true (?_switch_user=username)
           pattern: ^/
           anonymous: ~
           form_login:
              login_path: /login
              check_path: /login_check
           logout:
              path: /logout
              target: /

    access_control:
              - {path: ^/admin, roles: [ROLE_USER, ROLE_ADMIN]}
              - {path: ^/profile, roles: [ROLE_USER, ROLE_ADMIN]}

    providers:
              database_provider:
                     entity: {class: JohnUsersBundle:User, property: email}

    encoders:
         John\UsersBundle\Entity\User: sha512