

john_savant_login:
    pattern: /login
    defaults: { _controller: JohnSavantBundle:Security:login }

john_savant_logout:
    pattern: /logout

john_savant_login_check:
    pattern: /login_check

john_savant_homepage:
    pattern:  /
    defaults: { _controller: JohnSavantBundle:Default:index }

john_savant_register:
    pattern: /register
    defaults: { _controller: JohnSavantBundle:Register:index}

john_savant_captcha:
    pattern: /captcha/{random}
    defaults: { _controller: JohnSavantBundle:Captcha:index,random:0}

john_savant_profile:
    pattern: /profile
    defaults: {_controller:JohnSavantBundle:Profile:index}

john_savant_profile_edit:
    pattern: /profile/edit/{id}
    defaults: {_controller:JohnSavantBundle:Profile:edit}

john_savant_profile_change_password:
    pattern: /profile/change/pass
    defaults: {_controller:JohnSavantBundle:Profile:changePassword}




