
john_users_login:
    pattern: /login
    defaults: { _controller: JohnUsersBundle:Security:login }

john_users_logout:
    pattern: /logout

john_users_login_check:
    pattern: /login_check


john_users_register:
    pattern: /register
    defaults: { _controller: JohnUsersBundle:Register:index}

john_users_captcha:
    pattern: /captcha/{random}
    defaults: { _controller: JohnUsersBundle:Captcha:index,random:0}






