<?php

namespace John\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

    /**
     * @return array Return the asociative array ["slug"=>"name"] to display in Filter Form (select html element)
     */
    public function getSlugNamePairs()
    {
        $qb=$this->createQueryBuilder('c')
            ->select('c.slug, c.name');

        $results = $qb->getQuery()->getArrayResult();



        foreach($results as $result){

            $choices[$result['slug']]=$result['name'];
        }

        return $choices;
    }
}
