john_users_profile:
    pattern: /
    defaults: {_controller:JohnProfileBundle:Profile:index}

john_users_profile_edit:
    pattern: /edit/{id}
    defaults: {_controller:JohnProfileBundle:Profile:edit}

john_users_profile_change_password:
    pattern: /change/pass
    defaults: {_controller:JohnProfileBundle:Profile:changePassword}

p_article_new:
    pattern : /articles/new
    defaults: { _controller: JohnArticleBundle:Article:new}



p_article_create:
    pattern : /articles/create
    defaults: { _controller: JohnArticleBundle:Article:create}

p_article_show:
    pattern: /articles/{id}/show
    defaults: {_controller: JohnArticleBundle:Article:show}
    requirements:
        id: \d+

p_article_delete:
    pattern: /articles/{id}/delete
    defaults: {_controller: JohnArticleBundle:Article:delete}
    requirements:
        id: \d+

p_article_edit:
     pattern: /articles/{id}/edit
     defaults: {_controller: JohnArticleBundle:Article:edit}
     requirements:
          id: \d+

p_article_publish:
      pattern: /article/{id}/publish
      defaults: {_controller: JohnArticleBundle:Article:publish}
      requirements:
            id: \d+

p_article_update:
        pattern: /articles/{id}/update
        defaults: {_controller: JohnArticleBundle:Article:update}
        requirements:
             id: \d+

p_article_ckeditor_browse:
      pattern: /ckeditor/browse
      defaults: {_controller: JohnArticleBundle:CKEditor:browse}

p_article_ckeditor_upload:
      pattern: /ckeditor/upload
      defaults: {_controller: JohnArticleBundle:CKEditor:upload}

p_articles:
    pattern: /articles/{category}/{page}
    defaults: { _controller: JohnArticleBundle:Article:index,category:'all',page:1}
    requirements:
           category: \w+
           page: \d+

