john_users_profile:
    pattern: /
    defaults: {_controller:JohnProfileBundle:Profile:index}

john_users_profile_edit:
    pattern: /edit/{id}
    defaults: {_controller:JohnProfileBundle:Profile:edit}

john_users_profile_change_password:
    pattern: /change/pass
    defaults: {_controller:JohnProfileBundle:Profile:changePassword}

john_admin_articles:
    resource: "@JohnArticleBundle/Resources/config/routing.yml"
